### ISSUE TITLE
Throw event in case cherrypy fails to create server

### ISSUE THREAD

**Issue by dexpetkovic** [groupby/hubot-hangups#24]
As user
when I start hubot process with hubot-hangups integration
I want to be able to see in logs
if for any reason cherrypy failed to create server
i.e. due to already occupied port on the server.

**Comment by ehacke** [comment]
@dexpetkovic Yes, this is actually two issues that we need to fix.
1. Need to properly output all stdout from HangoutsBot and Hangups
2. Need to automatically assign an available port for the cherrypy server
